---
on:
  push:
    branches:
      - main
jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Run docker scraper
        env:
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
          TYPESENSE_PORT: 443
          TYPESENSE_PROTOCOL: https
        run: |
          docker run -e "CONFIG=$(cat scrapper_config.json | jq -r tostring)" typesense/docsearch-scraper
