---
on:
  push:
    branches:
      - main
jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Run docker scraper
        run: |
          docker run -e "TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY }}" -e "TYPESENSE_HOST=${{ secrets.TYPESENSE_HOST }}" -e "TYPESENSE_PORT=443" -e "TYPESENSE_PROTOCOL=https"  -e "CONFIG=$(cat $GITHUB_WORKSPACE/scrapper_config.json | jq -r tostring)" typesense/docsearch-scraper
